package:
  name: perl-http-daemon
  version: "6.12"

source:
  url: https://cpan.metacpan.org/authors/id/O/OA/OALDERS/HTTP-Daemon-6.12.tar.gz
  sha256: df47bed10c38670c780fd0116867d5fd4693604acde31ba63380dce04c4e1fa6

build:
  noarch: generic
  number: 0

requirements:
  host:
    - perl
    - perl-http-date
    - perl-http-message
    - perl-lwp-mediatypes

  run:
    - perl
    - perl-http-date
    - perl-http-message
    - perl-lwp-mediatypes

test:
  # Perl 'use' tests
  imports:
    - HTTP::Daemon

about:
  home: http://metacpan.org/pod/HTTP-Daemon
  license: perl_5
  summary: 'a simple http server class'
