package:
  name: perl-http-daemon
  version: "6.13"

source:
  url: https://cpan.metacpan.org/authors/id/O/OA/OALDERS/HTTP-Daemon-6.13.tar.gz
  sha256: d184d1f3e51e690d60e4b00195aa69f679169c858f2aab419997c70892014516

build:
  noarch: generic
  number: 0

requirements:
  host:
    - perl
    - perl-http-date
    - perl-http-message
    - perl-lwp-mediatypes

  run:
    - perl
    - perl-http-date
    - perl-http-message
    - perl-lwp-mediatypes

test:
  # Perl 'use' tests
  imports:
    - HTTP::Daemon

about:
  home: http://metacpan.org/pod/HTTP-Daemon
  license: perl_5
  summary: 'a simple http server class'
