{% set version = "0.1.0" %}

package:
  name: mudskipper
  version: {{ version }}

build:
  number: 0

source:
  url: https://github.com/OceanGenomics/mudskipper/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 9b931856d493182e29f995845bcf0860005fa221019c0e3e214ed7e670545eb0

requirements:
  build:
    - rust >=1.51  
    - cmake
    - autoconf
    - make
    - {{ compiler('cxx') }}
    - pkg-config
  host:
  run:

test:
  commands:
    - mudskipper --help

about:
  home: https://github.com/OceanGenomics/mudskipper
  license: BSD 3-Clause
  license_file: LICENSE
  summary: mudskipper is a tool for converting genomic BAM/SAM files to transcriptomic BAM/RAD files.