{% set name = "perl-bignum" %}
{% set version = "0.64" %}
{% set sha256 = "2f495442d8396740933f68688fb22133ec544ac72a4ca21df6032f80e558eaeb" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/P/PJ/PJACKLAM/bignum-0.64.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0

requirements:
  build:
    - make
  host:
    - perl
    - perl-extutils-makemaker
    - perl-math-bigint
    - perl-math-bigrat

  run:
    - perl
    - perl-math-bigint
    - perl-math-bigrat

test:
  imports:
    - bignum

about:
  home: http://metacpan.org/pod/bignum
  license: perl_5
  summary: 'Transparent BigNumber support for Perl'
