{% set name = "perl-mac-systemdirectory" %}
{% set version = "0.13" %}
{% set sha256 = "8730740e4ff3ea4812139b0787dbd1b544e093a08218d908071629b70fde3684" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/E/ET/ETHER/Mac-SystemDirectory-0.13.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0
  skip: True  # [not osx]

requirements:
  host:
    - perl
    - perl-exporter
    - perl-extutils-makemaker
    - perl-xsloader

  run:
    - perl
    - perl-exporter
    - perl-xsloader

test:
  imports:
    - Mac::SystemDirectory

about:
  home: https://github.com/chansen/p5-Mac-SystemDirectory
  license: perl_5
  summary: 'Locate Mac OS X Standard System Directories'

