package:
  name: perl-file-listing
  version: "6.14"

source:
  url: https://cpan.metacpan.org/authors/id/P/PL/PLICEASE/File-Listing-6.14.tar.gz
  sha256: 15b3a4871e23164a36f226381b74d450af41f12cc94985f592a669fcac7b48ff

build:
  noarch: generic
  number: 0

requirements:
  build:
    - make
  host:
    - perl
    - perl-http-date

  run:
    - perl
    - perl-http-date

test:
  # Perl 'use' tests
  imports:
    - File::Listing

about:
  home: http://metacpan.org/pod/File-Listing
  license: perl_5
  summary: 'parse directory listing'
